### ISSUE TITLE
Lost initialDate

### ISSUE THREAD

**Issue by Freyien** [ikicodedev/calendar_timeline#11]
First, i would like to congratulate you for this package, it's awesome.

When the calendar starts with an initial date, is ok.

when I browse for another month and return to the current date it is no longer selected.
this happens with the example.

Tanks, and sorry for my limit english.

**Comment by ikicodedev** [comment]
I understand that you are testing version 0.6.2. I have done the test and I do not reproduce the error you say. You may not have fully understood the problem you describe. If this latest version keeps happening to you, can you describe it a little more in depth?

PD: By your name I understand that you speak Spanish. If you want you can send me an email in Spanish to jose@codigobase.es explaining the error a little more.

**Comment by Freyien** [comment]
Thanks!! I sended the email with the data.

**Comment by ikicodedev** [comment]
We have created a new issue with the information provided #12
