### ISSUE TITLE
Locale with "nl" value loads error : "Value not in range: 3"

### ISSUE THREAD

**Issue by legrandced** [ikicodedev/calendar_timeline#13]
Hi,

First of all, thank you for this package ! It's very useful for me ! 👍 

I get the following error when trying to use the "**nl**" locale :

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following RangeError was thrown building:
**Value not in range: 3**

When the exception was thrown, this was the stack: 
#0      _StringBase.substring (dart:core-patch/string_patch.dart:388:7)
#1      _CalendarTimelineState._buildDayList.<anonymous closure> **(package:calendar_timeline/calendar_timeline.dart:134:22)**
#2      _PositionedListState._buildItem (package:scrollable_positioned_list/src/positioned_list.dart:247:54)
#3      _PositionedListState.build.<anonymous closure> (package:scrollable_positioned_list/src/positioned_list.dart:183:27)
#4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:22)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

The error is inside (package:calendar_timeline/**calendar_timeline.dart**) at **line 134** :

**DateFormat.E(_locale).format(currentDay).substring(0, 3).capitalize()**

Could you please check this out ?

Than you very much ! 👍 👍

**Comment by ikicodedev** [comment]
Thanks for the report @legrandced. Fixed in version 0.6.3
