### ISSUE TITLE
Because calendar_timeline >=0.6.1 depends on intl ^0.16.1 and fassernate depends on intl ^0.17.0, calendar_timeline >=0.6.1 is forbidden.

### ISSUE THREAD

**Issue by eltonlfasser** [ikicodedev/calendar_timeline#22]
Because calendar_timeline >=0.6.1 depends on intl ^0.16.1 and fassernate depends on intl ^0.17.0, calendar_timeline >=0.6.1 is forbidden.

**Comment by zerodice0** [comment]
flutter version and flutter_localization is updated so if you use recent version of flutter, you need to intl 0.17.0. but calendar_timeline is still has dependency to intl v0.16.1, so occur this problem.

**Comment by ikicodedev** [comment]
While we solve the problem you can use this intermediate solution. Add to pubspect.yaml:
```
dependency_overrides:
  intl: ^0.17.0
```

**Comment by GJJ2019** [comment]
Checkout pull request #24

**Comment by ikicodedev** [comment]
Closed in #24
