### ISSUE TITLE
Does not work with Flutter 2.0 (Cannot run with sound null safety)

### ISSUE THREAD

**Issue by alisolanki** [ikicodedev/calendar_timeline#27]
The following error pops up when trying to run using Flutter 2.0

```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:calendar_timeline
 - package:scrollable_positioned_list

For solutions, see https://dart.dev/go/unsound-null-safety
```

**Comment by alisolanki** [comment]
Just saw the repo in order to fix the issue. I think the problem has been solved but not published yet.

**Comment by ikicodedev** [comment]
You can use pre-release https://pub.dev/packages/calendar_timeline/versions/1.0.0-null-safety.0/install
