### ISSUE TITLE
After upgrade: Build failed due to use of deprecated Android v1 embedding.

### ISSUE THREAD

**Issue by sharpsaravanan** [ikicodedev/calendar_timeline#40]
The detected reason was:
  C:\Users\sharp\Downloads\calendar_timeline-1.0.4\example\android\app\src\main\AndroidManifest.xml uses `android:name="io.flutter.app.FutterApplication"`

Build failed due to use of deprecated Android v1 embedding.

**Comment by ikicodedev** [comment]
This will be resolved in the new version 1.0.5
