### ISSUE TITLE
Overflowed by 1.00 Pixel

### ISSUE THREAD

**Issue by AasharWahla** [ikicodedev/calendar_timeline#41]
![simulator_screenshot_34C144E1-C0CF-4CF3-9139-ABF5F2FABD16](https://user-images.githubusercontent.com/48863334/161405903-6176eae3-cea0-4ac6-9f20-14861b1ddf98.png)

Getting this particular issue, on the selected date only.

**Comment by globalwebforce** [comment]
Any Update?!?!?!

**Comment by ikicodedev** [comment]
Sorry, I'm very busy with work and right now I don't have much time to review bugs.

**Comment by ikicodedev** [comment]
Solved in version 1.1.1
