### ISSUE TITLE
Getting Warning after Flutter 3 Upgrade 🪲

### ISSUE THREAD

**Issue by sinnoorc** [ikicodedev/calendar_timeline#44]
**I am getting below warning message 👉**

Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/Users/sinno/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
      SchedulerBinding.instance!.addPostFrameCallback((_) {

**Comment by ZachGonzalezz** [comment]
I am getting this too. It appears the package relies on an old version  (pre flutter 3) of the package "scrollable_positioned_list".
