### ISSUE TITLE
Day wont change when use a async function onDateSelected

### ISSUE THREAD

**Issue by thivankasarathchandra** [ikicodedev/calendar_timeline#46]
`onDateSelected: (date) => setState(() {}),`

setSate does work when i select on the date, but the date does not update in the UI.

**Comment by xyther14** [comment]
Did you try updating the selectedDate in the setState?

**Comment by ikicodedev** [comment]
Hi @thivankasarathchandra, As @xyther14 says you must update the selectedDate variable inside the setState. You can see the code in the example folder of the package.
