### ISSUE TITLE
A RenderFlex overflowed by 3.0 pixels on the bottom.

### ISSUE THREAD

**Issue by nadeemabualarayes** [ikicodedev/calendar_timeline#53]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/66251426/209467301-2ecb6eb8-d420-49f2-be31-83f709ce9e0d.png">

**Comment by manueljishi** [comment]
I just updated to the new version and the same is happening to me. 
Did you find a way to solve this issue?
Thank youv very much

**Comment by 3g015st** [comment]
Currently experiencing the same issue 😞

**Comment by manueljishi** [comment]
Hi @3g015st this happened to me when I decided to update my flutter package to the newest version (1.1.0, i think) and I managed to solve it just by downgrading to the previous version (1.0.5) which has the same functionality but does not have this bug.
Hope this helps

**Comment by kwul0208** [comment]
i solve it by edit manually in _buildDayList() and change height of SizedBox() to 104

**Comment by juniormalcom237** [comment]
@kwul0208  not good practice but works. I'm just experiencing it.

**Comment by bubuzzz** [comment]
i got the same issue and it is very annoying. At first i thought it is because my container is not good thus  i tried to change all the heights of the parent containers until i realized that it is because the lib does not render correctly. Do we have any plan to fix this ?

**Comment by ikicodedev** [comment]
Solved in version 1.1.1
