### ISSUE TITLE
Changing/Resetting the initial date does not return the view to the appropriate date

### ISSUE THREAD

**Issue by wsegatto** [ikicodedev/calendar_timeline#7]
Using the example, I have set the first day as now() and the last date as 6 months from now. 
If I scroll right towards the end of the month and press RESET in the example code, the Calendar only scrolls a little bit to the left, not the entire way to the initial date as it was supposed to be.
You must press the button several times for it to go back to the initial date.

By the way, great job guys!

Edit: 
I must hot reload when changing start dates, otherwise the reset button will go crazy. Not sure that's intended, but it's how it behaves apparently.

**Comment by wsegatto** [comment]
Strange, I'm suddenly not able to reproduce it anymore now... I'll keep trying.

**Comment by wsegatto** [comment]
I got it. Must hot reload when changing start dates, otherwise the reset button will go crazy. Not sure that's intended, but it's how it behaves apparently.

**Comment by ikicodedev** [comment]
Can you attach the code that reproduces this error?

**Comment by ikicodedev** [comment]
We could not reproduce the error.
