### ISSUE TITLE
SetState in onDateSelected

### ISSUE THREAD

**Issue by OpticNectar** [ikicodedev/calendar_timeline#8]
Calling `SetState` in the `onDateSelected` call back causes the calendar to not work. When you click a day it just does nothing.

**Comment by ikicodedev** [comment]
I cannot reproduce the error. What version of the package are you using? Can you share the code example that gives you this error?

**Comment by OpticNectar** [comment]
I mentioned this in another bug, but if you use the code below and click any day, nothing happens.

```
CalendarTimeline(
  initialDate: DateTime.now(),
  firstDate: DateTime.now(),
  lastDate: DateTime.now().add(Duration(days: 7)),
  onDateSelected: (date) {
    setState(() {
      startDate = date;
    });
  },
)

```

**Comment by ikicodedev** [comment]
Duplicate of #9
