### ISSUE TITLE
DateTime.now issue

### ISSUE THREAD

**Issue by OpticNectar** [ikicodedev/calendar_timeline#9]
If you use `DateTime.now()` for the date fields such as `initialDate`, when the calendar reloads it does not keep the currently selected date. I'm guessing it is using the time for the DateTime and not just the date portion.

**Comment by ikicodedev** [comment]
Can you share the code example that gives you this error?

**Comment by OpticNectar** [comment]
A fresh flutter project with either 0.6.1 or 0.6.2 has the issue. If you run the code below and try to select a date, nothing happens. If you comment out `setState`, but keep the `startDate` part, it will work, but as soon as anything on the page runs `setState` the calendar selects the first day again. For example, if you add the calendar to the sample project new flutter projects come with and you click the plus fab, it makes the date change back to the first day.

```
CalendarTimeline(
  initialDate: DateTime.now(),
  firstDate: DateTime.now(),
  lastDate: DateTime.now().add(Duration(days: 7)),
  onDateSelected: (date) {
    setState(() {
      startDate = date;
    });
  },
)

```

**Comment by ikicodedev** [comment]
This is not a package error, it is an implementation error. By invoking `setState` the widget is rebuilt and as in the `initialDate` parameter you have indicated to take today's date, when selecting a date it is always updated to the current day. The correct example would be:

```
@override
  void initState() {
    startDate = Date.now();
  }

.....

CalendarTimeline(
  initialDate: startDate,
  firstDate: DateTime.now(),
  lastDate: DateTime.now().add(Duration(days: 7)),
  onDateSelected: (date) {
    setState(() {
      startDate = date;
    });
  },
)
```
